"""Property-based tests for response models and endpoint params().

These tests verify structural invariants that must hold for all valid inputs:

- **Roundtrip**: ``model_validate(model_dump(by_alias=True))`` reconstructs an
  equal model for any valid instance generated by ``model_strategy()``.
- **Params keys**: ``Endpoint.params()`` always returns exactly the expected set
  of API parameter names — for any valid construction, not just hand-picked
  examples.
- **Params values**: every value in ``params()`` is a ``str`` and matches the
  corresponding field on the endpoint.
"""

import pytest
from hypothesis import HealthCheck, given, settings

from fastbreak.endpoints.box_score_advanced import BoxScoreAdvanced
from fastbreak.endpoints.box_score_four_factors import BoxScoreFourFactors
from fastbreak.endpoints.box_score_matchups import BoxScoreMatchups
from fastbreak.endpoints.box_score_misc import BoxScoreMisc
from fastbreak.endpoints.box_score_player_track import BoxScorePlayerTrack
from fastbreak.endpoints.box_score_scoring import BoxScoreScoring
from fastbreak.endpoints.box_score_summary import BoxScoreSummary
from fastbreak.endpoints.box_score_traditional import BoxScoreTraditional
from fastbreak.endpoints.box_score_usage import BoxScoreUsage
from fastbreak.endpoints.league_dash_player_stats import LeagueDashPlayerStats
from fastbreak.endpoints.league_standings import LeagueStandings
from fastbreak.models import TeamStanding

from tests.strategies import model_strategy

_XDIST = [HealthCheck.differing_executors]


# ===========================================================================
# Roundtrip: model_validate(model_dump(by_alias=True)) == original
# ===========================================================================


class TestTeamStandingRoundtrip:
    """Roundtrip property for TeamStanding (92-field response model).

    TeamStanding is a good representative: it has str, int, float, and
    int | None fields, all accessed via CamelCase aliases.
    """

    @given(standing=model_strategy(TeamStanding))
    @settings(max_examples=50, suppress_health_check=_XDIST)
    def test_roundtrip_via_alias_dump(self, standing: TeamStanding) -> None:
        """model_dump(by_alias=True) round-trips through model_validate."""
        data = standing.model_dump(by_alias=True)
        assert TeamStanding.model_validate(data) == standing

    @given(standing=model_strategy(TeamStanding))
    @settings(max_examples=50, suppress_health_check=_XDIST)
    def test_dump_contains_all_alias_keys(self, standing: TeamStanding) -> None:
        """model_dump(by_alias=True) has an entry for every declared field."""
        data = standing.model_dump(by_alias=True)
        for name, field in TeamStanding.model_fields.items():
            key = field.alias or name
            assert key in data, f"missing key {key!r} (field {name!r})"


# ===========================================================================
# GameIdEndpoint family — all box score endpoints share one params() shape
# ===========================================================================

_BOX_SCORE_ENDPOINTS = [
    BoxScoreAdvanced,
    BoxScoreFourFactors,
    BoxScoreMatchups,
    BoxScoreMisc,
    BoxScorePlayerTrack,
    BoxScoreScoring,
    BoxScoreSummary,
    BoxScoreTraditional,
    BoxScoreUsage,
]


@pytest.mark.parametrize("cls", _BOX_SCORE_ENDPOINTS, ids=lambda c: c.__name__)
def test_game_id_endpoint_params(cls) -> None:
    """Every GameIdEndpoint.params() returns exactly {'GameID': game_id}."""

    @given(ep=model_strategy(cls))
    @settings(max_examples=20, suppress_health_check=_XDIST)
    def _inner(ep) -> None:
        assert ep.params() == {"GameID": ep.game_id}

    _inner()


# ===========================================================================
# LeagueStandings — verify key names and value-to-field mapping
# ===========================================================================


class TestLeagueStandingsParams:
    """LeagueStandings.params() must expose all three params with correct keys."""

    @given(ep=model_strategy(LeagueStandings))
    @settings(max_examples=50, suppress_health_check=_XDIST)
    def test_params_exactly_match_fields(self, ep: LeagueStandings) -> None:
        """params() maps every field to its exact API key name."""
        assert ep.params() == {
            "LeagueID": ep.league_id,
            "Season": ep.season,
            "SeasonType": ep.season_type,
        }


# ===========================================================================
# LeagueDashPlayerStats — large endpoint with many optional string filters
# ===========================================================================


class TestLeagueDashPlayerStatsParams:
    """LeagueDashPlayerStats.params() must produce a valid dict[str, str]."""

    @given(ep=model_strategy(LeagueDashPlayerStats))
    @settings(max_examples=30, suppress_health_check=_XDIST)
    def test_all_params_are_strings(self, ep: LeagueDashPlayerStats) -> None:
        """Every params() value is a str, including int fields converted via str()."""
        params = ep.params()
        for k, v in params.items():
            assert isinstance(v, str), (
                f"params()[{k!r}] = {v!r} — expected str, got {type(v).__name__}"
            )

    @given(ep=model_strategy(LeagueDashPlayerStats))
    @settings(max_examples=30, suppress_health_check=_XDIST)
    def test_season_and_league_id_reflect_fields(
        self, ep: LeagueDashPlayerStats
    ) -> None:
        """Core params map directly to their endpoint fields."""
        params = ep.params()
        assert params["Season"] == ep.season
        assert params["LeagueID"] == ep.league_id
        assert params["PerMode"] == ep.per_mode
        assert params["MeasureType"] == ep.measure_type

    @given(ep=model_strategy(LeagueDashPlayerStats))
    @settings(max_examples=30, suppress_health_check=_XDIST)
    def test_optional_filter_params_reflect_fields(
        self, ep: LeagueDashPlayerStats
    ) -> None:
        """Optional filter fields (Conference, Division, …) appear as-is in params."""
        params = ep.params()
        assert params["Conference"] == ep.conference
        assert params["Division"] == ep.division
        assert params["Location"] == ep.location
